### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by anusha7530** [edgexhq/brave#42]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Girlscript-WOB/Guidelines/blob/main/Project%20Admins/Code%20of%20conduct.md

**Comment by KiranBaliga** [comment]
Please assign this task to me as a part of WOB24 Contribution @uiuxarghya @Xeven777 @subhadeeproy3902 Thank you

**Comment by subhadeeproy3902** [comment]
Sure ! @KiranBaliga

**Comment by KiranBaliga** [comment]
@subhadeeproy3902 anusha is the member of the WoB team who set up the issue for the repo. If you would like me to work on it, please assign to me. I know WoB and GSSoC24 is done, but I can still work if you would give a chance.

**Comment by subhadeeproy3902** [comment]
go ahead @KiranBaliga

**Comment by KiranBaliga** [comment]
@subhadeeproy3902 Please review the PR and action accordingly. Thank you!

**Comment by KiranBaliga** [comment]
@subhadeeproy3902 please review.
